services:
  catatsehat:
    image: yudhapwa/catat-sehat:dev
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 1024M
    ports:
      - "5000:3000"
    env_file:
      - /home/emokids/tugas-akhir/catatsehat/.env.dev
    networks:
      - postgres-network

networks:
  postgres-network:
    external: true
