services:
  catatsehat:
    image: yudhapwa/catat-sehat:dev
    restart: unless-stopped
    ports:
      - "8081:3000"
    env_file:
      - /home/emokids/tugas-akhir/catatsehat/.env.dev
    networks:
      - minio-network
      - postgres-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s

networks:
  minio-network:
    name: minio-network
    external: true
  postgres-network:
    name: postgres-network
    external: true
