services:
  app-dev:
    container_name: catatsehat-dev
    image: yudhapwa/catat-sehat:dev
    ports:
      - "8081:3000"
    env_file:
      - /home/emokids/tugas-akhir/catatsehat/.env.dev
    networks:
      - minio-network
      - postgres-network
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s

networks:
  minio-network:
    name: minio-network
    external: true

  postgres-network:
    name: postgres-network
    external: true
