services:
  catatsehat:
    image: yudhapwa/catat-sehat:dev
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 512M
      update_config:
        parallelism: 1
        delay: 10s
    ports:
      - "8080:3000"
    env_file:
      - /home/emokids/tugas-akhir/catatsehat/.env.dev
    networks:
      - minio-network
      - postgres-network

networks:
  minio-network:
    external: true
  postgres-network:
    external: true
