services:
  app-dev:
    container_name: catatsehat-dev
    image: yudhapwa/catat-sehat:dev
    pull_policy: always
    ports:
      - "3000:3005"
    env_file:
      - /home/wawan/catatsehat/.env.dev
    networks:
      - minio-network
      - postgres-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s

networks:
  minio-network:
    name: minio-network
    external: true

  postgres-network:
    name: postgres-network
    external: true
