name: Development Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Dev Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/catat-sehat:dev

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Copy files to VPS
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.PORT }}
          source: "."
          target: "/home/emokids/tugas-akhir/catatsehat/tmp"

      - name: Deploy to Dev Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/emokids/tugas-akhir/catatsehat/tmp

            echo "✅ Pull image terbaru..."
            docker pull yudhapwa/catat-sehat:dev

            echo "🚀 Deploy stack..."
            docker stack deploy -c catatsehat-stack.yml catatsehat

            echo "🧹 Membersihkan image yang tidak terpakai..."
            docker image prune -af --filter "label!=keep"

            echo "🗑️ Hapus sementara file pipeline..."
            rm -rf /home/emokids/tugas-akhir/catatsehat/tmp/*
